name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Stop running bot
      run: |
        pkill -f "python main.py"
        sleep 5  # Add a delay to ensure the bot is stopped properly
      
    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install python3.9
        python3 -m pip install --upgrade pip


    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run bot
      run: python main.py
